/**
 * Config - Written by Benjamin Jack Cullen.
 *
*/

#include <Arduino.h>
#include <Wire.h>
#include "config.h"

bool global_task_sync      = false;
long system_sync_retry_max = 10000;

/**
 * @brief Global IIC wire instances and data struictures for each wire channel.
 */
// TwoWire iic_0(0); // wire channel 0
// TwoWire iic_1(1); // wire channel 1
// TwoWire iic_2(2); // wire channel 2

struct PwrConfig pwrConfigLowPower = {
    .name = {"Low Power"},

    .TASK_MAX_FREQ_MS_GPS = TASK_MAX_FREQ_MS_LOW_GPS,

    .TASK_MAX_FREQ_MS_INFOCMD = TASK_MAX_FREQ_MS_LOW_SERIAL_INFOCMD,

    .TASK_MAX_FREQ_MS_MULTIPLEXERS = TASK_MAX_FREQ_MS_LOW_MULTIPLEXERS,

    .TASK_MAX_FREQ_MS_GYRO = TASK_MAX_FREQ_MS_LOW_GYRO,

    .TASK_MAX_FREQ_MS_UNIVERSE = TASK_MAX_FREQ_MS_LOW_UNIVERSE,

    .TASK_MAX_FREQ_MS_SWITCHES = TASK_MAX_FREQ_MS_LOW_SWITCHES,

    .TASK_MAX_FREQ_MS_PORTCONTROLLER_INPUT = TASK_MAX_FREQ_MS_LOW_PORTCONTROLLER_INPUT,

    .TASK_MAX_FREQ_MS_STORAGE = TASK_MAX_FREQ_MS_LOW_STORAGE,

    .TASK_MAX_FREQ_MS_DISPLAY = TASK_MAX_FREQ_MS_LOW_DISPLAY,

    .TASK_MAX_FREQ_MS_SYSTEM_TIME = TASK_MAX_FREQ_MS_LOW_SYSTEM_TIME,
};

struct PwrConfig pwrConfigBalanced = {
    .name = {"Balanced"},

    .TASK_MAX_FREQ_MS_GPS = TASK_MAX_FREQ_MS_BALANCED_GPS,

    .TASK_MAX_FREQ_MS_INFOCMD = TASK_MAX_FREQ_MS_BALANCED_SERIAL_INFOCMD,

    .TASK_MAX_FREQ_MS_MULTIPLEXERS = TASK_MAX_FREQ_MS_BALANCED_MULTIPLEXERS,

    .TASK_MAX_FREQ_MS_GYRO = TASK_MAX_FREQ_MS_BALANCED_GYRO,

    .TASK_MAX_FREQ_MS_UNIVERSE = TASK_MAX_FREQ_MS_BALANCED_UNIVERSE,

    .TASK_MAX_FREQ_MS_SWITCHES = TASK_MAX_FREQ_MS_BALANCED_SWITCHES,

    .TASK_MAX_FREQ_MS_PORTCONTROLLER_INPUT = TASK_MAX_FREQ_MS_BALANCED_PORTCONTROLLER_INPUT,

    .TASK_MAX_FREQ_MS_STORAGE = TASK_MAX_FREQ_MS_BALANCED_STORAGE,

    .TASK_MAX_FREQ_MS_DISPLAY = TASK_MAX_FREQ_MS_BALANCED_DISPLAY,

    .TASK_MAX_FREQ_MS_SYSTEM_TIME = TASK_MAX_FREQ_MS_BALANCED_SYSTEM_TIME,
};

struct PwrConfig pwrConfigUltimatePerformance = {
    .name = {"Ultimate Performance"},

    .TASK_MAX_FREQ_MS_GPS = TASK_MAX_FREQ_MS_HIGH__GPS,

    .TASK_MAX_FREQ_MS_INFOCMD = TASK_MAX_FREQ_MS_HIGH__SERIAL_INFOCMD,

    .TASK_MAX_FREQ_MS_MULTIPLEXERS = TASK_MAX_FREQ_MS_HIGH__MULTIPLEXERS,

    .TASK_MAX_FREQ_MS_GYRO = TASK_MAX_FREQ_MS_HIGH__GYRO,

    .TASK_MAX_FREQ_MS_UNIVERSE = TASK_MAX_FREQ_MS_HIGH__UNIVERSE,

    .TASK_MAX_FREQ_MS_SWITCHES = TASK_MAX_FREQ_MS_HIGH__SWITCHES,

    .TASK_MAX_FREQ_MS_PORTCONTROLLER_INPUT = TASK_MAX_FREQ_MS_HIGH__PORTCONTROLLER_INPUT,

    .TASK_MAX_FREQ_MS_STORAGE = TASK_MAX_FREQ_MS_HIGH__STORAGE,

    .TASK_MAX_FREQ_MS_DISPLAY = TASK_MAX_FREQ_MS_HIGH__DISPLAY,

    .TASK_MAX_FREQ_MS_SYSTEM_TIME = TASK_MAX_FREQ_MS_HIGH_SYSTEM_TIME,
};

/**
 * @brief Current power configuration for the system.
 * @note Setup as required (default set to Balanced).
 */
struct PwrConfig pwrConfigCurrent = pwrConfigBalanced;