#include <Arduino.h>
#include <Wire.h>
#include "config.h"

// ----------------------------------------------------------------------------------------
// Power & Performance – Real mutable variables with default values
// ----------------------------------------------------------------------------------------

long  DELAY_TASK_DISPLAY              = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_MULTI_DISPLAY;
bool  TICK_DELAY_TASK_DISPLAY         = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_MULTI_DISPLAY;

long  DELAY_TASK_SERIAL_INFOCMD       = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_SERIAL_INFOCMD;
bool  TICK_DELAY_TASK_SERIAL_INFOCMD  = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_SERIAL_INFOCMD;

long  DELAY_TASK_MULTIPLEXERS         = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_MULTIPLEXERS;
bool  TICK_DELAY_TASK_MULTIPLEXERS    = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_MULTIPLEXERS;


long  DELAY_TASK_GYRO0                = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_GYRO;
bool  TICK_DELAY_TASK_GYRO0           = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_GYRO;

long  DELAY_TASK_UNIVERSE             = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_UNIVERSE;
bool  TICK_DELAY_TASK_UNIVERSE        = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_UNIVERSE;

long  DELAY_TASK_GPS                  = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_GPS;
bool  TICK_DELAY_TASK_GPS             = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_GPS;

long  DELAY_TASK_SWITCHES             = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_SWITCHES;
bool  TICK_DELAY_TASK_SWITCHES        = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_SWITCHES;

long  DELAY_TASK_PORTCONTROLLER_INPUT      = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_PORTCONTROLLER_INPUT;
bool  TICK_DELAY_TASK_PORTCONTROLLER_INPUT = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_PORTCONTROLLER_INPUT;

long  DELAY_TASK_STORAGE              = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_STORAGE;
bool  TICK_DELAY_TASK_STORAGE         = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_STORAGE;

long  DELAY_TASK_LOGGING         = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_LOGGING;
bool  TICK_DELAY_TASK_LOGGING    = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_LOGGING;

bool global_task_sync      = false;
long system_sync_retry_max = 10000;

/**
 * @brief Global IIC wire instances and data struictures for each wire channel.
 */
// TwoWire iic_0(0); // wire channel 0
// TwoWire iic_1(1); // wire channel 1
// TwoWire iic_2(2); // wire channel 2