/**
 * Config - Written by Benjamin Jack Cullen.
 *
*/

#include <Arduino.h>
#include <Wire.h>
#include "config.h"

bool global_task_sync      = false;
long system_sync_retry_max = 10000;

/**
 * @brief Global IIC wire instances and data struictures for each wire channel.
 */
// TwoWire iic_0(0); // wire channel 0
// TwoWire iic_1(1); // wire channel 1
// TwoWire iic_2(2); // wire channel 2

struct PwrConfig pwrConfigLowPower = {
    .name = {"Low Power"},

    .TASK_TICKS_GPS = POWER_CONFIG_LOW_POWER_DELAY_TASK_GPS,
    .TASK_USE_TICKS_GPS = POWER_CONFIG_LOW_POWER_TICK_DELAY_TASK_GPS,

    .TASK_TICKS_INFOCMD = POWER_CONFIG_LOW_POWER_DELAY_TASK_SERIAL_INFOCMD,
    .TASK_USE_TICKS_INFOCMD = POWER_CONFIG_LOW_POWER_TICK_DELAY_TASK_SERIAL_INFOCMD,

    .TASK_TICKS_MULTIPLEXERS = POWER_CONFIG_LOW_POWER_DELAY_TASK_MULTIPLEXERS,
    .TASK_USE_TICKS_MULTIPLEXERS = POWER_CONFIG_LOW_POWER_TICK_DELAY_TASK_MULTIPLEXERS,

    .TASK_TICKS_GYRO = POWER_CONFIG_LOW_POWER_DELAY_TASK_GYRO,
    .TASK_USE_TICKS_GYRO = POWER_CONFIG_LOW_POWER_TICK_DELAY_TASK_GYRO,

    .TASK_TICKS_UNIVERSE = POWER_CONFIG_LOW_POWER_DELAY_TASK_UNIVERSE,
    .TASK_USE_TICKS_UNIVERSE = POWER_CONFIG_LOW_POWER_TICK_DELAY_TASK_UNIVERSE,

    .TASK_TICKS_SWITCHES = POWER_CONFIG_LOW_POWER_DELAY_TASK_SWITCHES,
    .TASK_USE_TICKS_SWITCHES = POWER_CONFIG_LOW_POWER_TICK_DELAY_TASK_SWITCHES,

    .TASK_TICKS_PORTCONTROLLER_INPUT = POWER_CONFIG_LOW_POWER_DELAY_TASK_PORTCONTROLLER_INPUT,
    .TASK_USE_TICKS_PORTCONTROLLER_INPUT = POWER_CONFIG_LOW_POWER_TICK_DELAY_TASK_PORTCONTROLLER_INPUT,

    .TASK_TICKS_STORAGE = POWER_CONFIG_LOW_POWER_DELAY_TASK_STORAGE,
    .TASK_USE_TICKS_STORAGE = POWER_CONFIG_LOW_POWER_TICK_DELAY_TASK_STORAGE,
};

struct PwrConfig pwrConfigBalanced = {
    .name = {"Balanced"},

    .TASK_TICKS_GPS = POWER_CONFIG_BALANCED_DELAY_TASK_GPS,
    .TASK_USE_TICKS_GPS = POWER_CONFIG_BALANCED_TICK_DELAY_TASK_GPS,

    .TASK_TICKS_INFOCMD = POWER_CONFIG_BALANCED_DELAY_TASK_SERIAL_INFOCMD,
    .TASK_USE_TICKS_INFOCMD = POWER_CONFIG_BALANCED_TICK_DELAY_TASK_SERIAL_INFOCMD,

    .TASK_TICKS_MULTIPLEXERS = POWER_CONFIG_BALANCED_DELAY_TASK_MULTIPLEXERS,
    .TASK_USE_TICKS_MULTIPLEXERS = POWER_CONFIG_BALANCED_TICK_DELAY_TASK_MULTIPLEXERS,

    .TASK_TICKS_GYRO = POWER_CONFIG_BALANCED_DELAY_TASK_GYRO,
    .TASK_USE_TICKS_GYRO = POWER_CONFIG_BALANCED_TICK_DELAY_TASK_GYRO,

    .TASK_TICKS_UNIVERSE = POWER_CONFIG_BALANCED_DELAY_TASK_UNIVERSE,
    .TASK_USE_TICKS_UNIVERSE = POWER_CONFIG_BALANCED_TICK_DELAY_TASK_UNIVERSE,

    .TASK_TICKS_SWITCHES = POWER_CONFIG_BALANCED_DELAY_TASK_SWITCHES,
    .TASK_USE_TICKS_SWITCHES = POWER_CONFIG_BALANCED_TICK_DELAY_TASK_SWITCHES,

    .TASK_TICKS_PORTCONTROLLER_INPUT = POWER_CONFIG_BALANCED_DELAY_TASK_PORTCONTROLLER_INPUT,
    .TASK_USE_TICKS_PORTCONTROLLER_INPUT = POWER_CONFIG_BALANCED_TICK_DELAY_TASK_PORTCONTROLLER_INPUT,

    .TASK_TICKS_STORAGE = POWER_CONFIG_BALANCED_DELAY_TASK_STORAGE,
    .TASK_USE_TICKS_STORAGE = POWER_CONFIG_BALANCED_TICK_DELAY_TASK_STORAGE,
};

struct PwrConfig pwrConfigUltimatePerformance = {
    .name = {"Ultimate Performance"},

    .TASK_TICKS_GPS = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_GPS,
    .TASK_USE_TICKS_GPS = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_GPS,

    .TASK_TICKS_INFOCMD = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_SERIAL_INFOCMD,
    .TASK_USE_TICKS_INFOCMD = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_SERIAL_INFOCMD,

    .TASK_TICKS_MULTIPLEXERS = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_MULTIPLEXERS,
    .TASK_USE_TICKS_MULTIPLEXERS = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_MULTIPLEXERS,

    .TASK_TICKS_GYRO = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_GYRO,
    .TASK_USE_TICKS_GYRO = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_GYRO,

    .TASK_TICKS_UNIVERSE = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_UNIVERSE,
    .TASK_USE_TICKS_UNIVERSE = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_UNIVERSE,

    .TASK_TICKS_SWITCHES = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_SWITCHES,
    .TASK_USE_TICKS_SWITCHES = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_SWITCHES,

    .TASK_TICKS_PORTCONTROLLER_INPUT = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_PORTCONTROLLER_INPUT,
    .TASK_USE_TICKS_PORTCONTROLLER_INPUT = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_PORTCONTROLLER_INPUT,

    .TASK_TICKS_STORAGE = POWER_CONFIG_ULTIMATE_PERFORMANCE_DELAY_TASK_STORAGE,
    .TASK_USE_TICKS_STORAGE = POWER_CONFIG_ULTIMATE_PERFORMANCE_TICK_DELAY_TASK_STORAGE,
};

/**
 * @brief Current power configuration for the system.
 * @note Setup as required (default set to Balanced).
 */
struct PwrConfig pwrConfigCurrent = pwrConfigBalanced;